### ISSUE TITLE
Nuxt 3.10.2 & RC.38 Not Found?

### ISSUE THREAD

**Issue by markus-gx** [nuxt-modules/og-image#165] opened 2024-02-22 06:16 UTC
OG:Image seems to be broken with Nuxt 3.10.2 and latest nuxt-og-image version at least in my setup. 

```
//nuxt.config.ts
site: {
    url: process.env.DOMAIN,
  },

export const modules: NuxtConfig['modules'] = [
  [
    '@storyblok/nuxt',
    {
      accessToken: process.env.STORYBLOK_API_KEY,
      useApiClient: true,
      componentsDir: false,
    },
  ],
  '@nuxtjs/tailwindcss',
  '@pinia/nuxt',
  '@nuxt/image',
  '@nuxtjs/turnstile',
  '@vueuse/nuxt',
  ['nuxt-jsonld', { disableOptionsAPI: true }],
  'nuxt-og-image',
  ...prodModules,
]
```

```
//[...slugs].vue
defineOgImageComponent('NuxtSeo')
```

<img width="1555" alt="image" src="https://github.com/nuxt-modules/og-image/assets/16301998/2a04b953-1487-46d0-b6e8-211e99fd4d77">

Any suggestions or fixes I can try? 
Thanks.

**Comment by just-maik** [comment] 2024-02-26 13:17
Having the same issue in my nuxt project. But when I try to create a [reproduction on stackblitz](https://stackblitz.com/edit/nuxt-starter-4abzfm?file=app.vue) it works...
I'm wondering if some nested routes or other modules are responsible 🤔

**Comment by just-maik** [comment] 2024-02-27 08:59
I think it's not because of modules but I'll dump my `nuxi info` result here. (I installed nuxt-og-image via @nuxtjs/seo)
- Operating System: Linux
- Node Version:     v18.17.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  bun@1.0.28
- User Config:      telemetry, modules, site, ogImage, sitemap, robots, seo, seoExperiments, linkChecker, nuxtRateLimit, devtools, tailwindcss, nitro, runtimeConfig, graphql-client, security, app
- Runtime Modules:  @nuxtjs/seo@2.0.0-rc.8, @vueuse/nuxt@10.8.0, @nuxtjs/device@3.1.1, nuxt-security@1.2.1, nuxt-graphql-client@0.2.33, nuxt-typed-router@3.6.1, nuxt-icon@0.6.8, @nuxt/image@1.3.0, @dargmuesli/nuxt-cookie-control@7.3.0, @nuxtjs/tailwindcss@6.11.4, nuxt-rate-limit@1.2.0, @formkit/auto-animate/nuxt@0.8.1

@markus-gx maybe you could do the same using `nuxi info`, just to see if there are any suspicious overlaps.

**Comment by markus-gx** [comment] 2024-03-04 07:11
Sure @just-maik 

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.5.1
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  yarn@4.0.2
- Builder:          -
- User Config:      srcDir, app, hooks, turnstile, runtimeConfig, css, components, modules, image, security, vite, extends
- Runtime Modules:  @storyblok/nuxt@6.0.4, @nuxtjs/tailwindcss@6.11.4, @pinia/nuxt@0.5.1, @nuxt/image@1.3.0, @nuxtjs/turnstile@0.6.3, @vueuse/nuxt@10.7.2, nuxt-jsonld@2.0.8, nuxt-security@1.1.2
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment] 2024-03-04 08:06
I'll need a reproduction to investigate further, there's a starter [here](https://stackblitz.com/edit/nuxt-starter-pxs3wk?file=pages/index.vue).

**Comment by just-maik** [comment] 2024-03-04 08:20
I suspect nuxt/security to be the culprit. But just to make sure before I try to reproduce this, are you doing any complex redirection / route logic that is not part of routeRules or the folder structure @markus-gx? Because that's part of my application and would be the only other possible cause that I can think of right now.

**Comment by markus-gx** [comment] 2024-03-06 17:23
It seems the reason is a catchAll route. 
```
pages/[...slugs].vue
```

After adding this OG:Image DevTools is not working anymore. Since I am using a CMS in the background the catchAll route is necessary to build pages. 

Reproduction: https://stackblitz.com/edit/nuxt-starter-8iz6ui?file=app.vue

**Comment by harlan-zw** [comment] 2024-03-07 00:46
Thanks, will investigate further in the next couple of days.

**Comment by harlan-zw** [comment] 2024-03-16 01:21
Seems to be fixed with RC 47 https://stackblitz.com/edit/nuxt-starter-enusw3?file=package.json

**Closed by harlan-zw** 2024-03-16 01:21 UTC
